version: '2'
services:
  redis:
    image: redis

  nginx:
    build:
      context: .
      dockerfile: DockerFileWeb
    ports:
      - "8080:90"

  driver:
    build:
      context: .
      dockerfile: DockerFileApi
    ports:
      - "4000:80"
    links:
      - redis
      - nginx

